from __future__ import annotations

import json
from typing import Any

from materials2textbook.domain_config import DomainConfig
from materials2textbook.schemas import EvidenceChunk


def build_book_plan_messages(
    *,
    title: str,
    chunks: list[EvidenceChunk],
    domain_config: DomainConfig,
    max_chapters: int = 12,
    max_chars: int = 14000,
) -> list[dict[str, str]]:
    samples = []
    for chunk in chunks[:160]:
        samples.append(
            {
                "chunk_id": chunk.chunk_id,
                "title": chunk.title,
                "summary": chunk.summary,
                "content": (chunk.content or "")[:500],
                "subject": chunk.subject,
                "material_block": chunk.material_block,
                "recommended_chapter": chunk.recommended_chapter,
                "source_type": chunk.source_type,
                "review_status": chunk.review_status,
            }
        )
    payload: dict[str, Any] = {
        "title": title,
        "domain_config": domain_config.to_dict(),
        "evidence_chunks": samples,
    }
    clipped = json.dumps(payload, ensure_ascii=False, indent=2)[:max_chars]
    system = (
        "You are a vocational project-based digital textbook planning agent. "
        "Create a complete, evidence-grounded project/task book plan. "
        "Return one strict JSON object and no Markdown."
    )
    user = "\n".join(
        [
            "Generate a whole-book plan for the provided evidence chunks.",
            "The final textbook must use this structure:",
            "总序",
            "前言",
            "项目1",
            "  项目导学",
            "  能力图谱",
            "  学习目标",
            "  任务1.1",
            "    学习导航",
            "    情境导入",
            "    任务实施",
            "    任务评价",
            "    思考与练习",
            "  任务1.2",
            "  任务1.3",
            "  项目小结",
            "项目2 ...",
            "",
            "In the JSON schema below, use chapters as projects and sections as tasks.",
            "Return this exact JSON shape:",
            "{",
            '  "title": "book title",',
            '  "chapters": [',
            "    {",
            '      "chapter_no": 1,',
            '      "title": "project title",',
            '      "learning_goals": ["goal 1", "goal 2"],',
            '      "sections": [',
            "        {",
            '          "section_no": "1.1",',
            '          "title": "task title",',
            '          "knowledge_points": ["point 1", "point 2"],',
            '          "primary_material_ids": ["existing_chunk_id"]',
            "        }",
            "      ]",
            "    }",
            "  ]",
            "}",
            "",
            "Hard rules:",
            "- Plan at least 3 projects and at most " + str(max_chapters) + " projects.",
            "- Every project must contain at least 3 tasks.",
            "- Every task must contain at least 1 knowledge point.",
            "- Number project tasks as 1.1, 1.2, 1.3 for project 1; 2.1, 2.2, 2.3 for project 2; and so on.",
            "- Do not create separate JSON sections for 项目导学, 能力图谱, 学习目标, or 项目小结; those are fixed project modules generated by the pipeline.",
            "- Every task will later be written with exactly these task modules: 学习导航, 情境导入, 任务实施, 任务评价, 思考与练习.",
            "- primary_material_ids must only use chunk_id values from the input.",
            "- Do not create projects from individual filenames.",
            "- Do not invent a project unrelated to the evidence.",
            "- Prefer balanced projects with enough evidence to support writing.",
            "",
            "Planning input:",
            clipped,
        ]
    )
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]
